Update the readme with instructions for setting up webots
NUbots/NUWebots pull request #12
Opened 2021-03-26 21:46 UTC by ysims

Windows needs more info. Hoping I've done something incredibly wrong which illuminates why I can't get the controller working :laughing:

2021-03-26 23:02 UTC, tayloryoung6396 commented
Windows is pretty straight forward, use the linux install instruction for webots using the wsl. You'll also need 
In Windows, install VcXsrc from https://sourceforge.net/projects/vcxsrv/
In Windows, run XLaunch and ensure the following settings are set
First screen:
Multiple Windows
Display number: -1
Second screen:
Start no client
Third screen:
Clipboard: Checked
Primary Selection: Checked
Native opengl: Unchecked
Disable: Checked
In WSL, install needed xcb libraries
sudo apt install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0 libxkbcommon0
In Windows, open a command prompt and run ipconfig. Look for an adapter that does NOT have vEthernet in its name and has a valid IPv4 Address, note it down
In WSL set the DISPLAY environment variable
export DISPLAY=<IPv4 Address from step 4>:0.0 
You can add to this command to the end of your ~/.bashrc file, but the IP address is likely to change every time you reboot Windows so you need to remember to update this command and re-source ~/.bashrc
In WSL, source the ~/.bashrc file if you have edited it. If you have not changed ~/.bashrc since the last time you started WSL then you should not need to do this, but it also shouldn't hurt
source ~/.bashrc
At this point you should now be able to run graphical applications (like the labeller) in WSL.

2021-03-26 23:12 UTC, Bidski commented
> Windows is pretty straight forward, use the linux install instruction for webots using the wsl. You'll also need
> In Windows, install VcXsrc from https://sourceforge.net/projects/vcxsrv/
> In Windows, run XLaunch and ensure the following settings are set
> First screen:
> Multiple Windows
> Display number: -1
> Second screen:
> Start no client
> Third screen:
> Clipboard: Checked
> Primary Selection: Checked
> Native opengl: Unchecked
> Disable: Checked
> In WSL, install needed xcb libraries
> sudo apt install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0 libxkbcommon0
> In Windows, open a command prompt and run ipconfig. Look for an adapter that does NOT have vEthernet in its name and has a valid IPv4 Address, note it down
> In WSL set the DISPLAY environment variable
> export DISPLAY=<IPv4 Address from step 4>:0.0
> You can add to this command to the end of your ~/.bashrc file, but the IP address is likely to change every time you reboot Windows so you need to remember to update this command and re-source ~/.bashrc
> In WSL, source the ~/.bashrc file if you have edited it. If you have not changed ~/.bashrc since the last time you started WSL then you should not need to do this, but it also shouldn't hurt
> source ~/.bashrc
> At this point you should now be able to run graphical applications (like the labeller) in WSL.

Also need to disable access control in VcXSrv settings

2021-03-29 02:48 UTC, KipHamiltons requested changes
Need to download/install webots first, before making the project

2021-03-29 02:49 UTC, KipHamiltons commented on README.md
> +    make
```suggestion
    make -j$(nproc)
```

2021-03-31 23:37 UTC, Bidski requested changes

2021-03-31 23:37 UTC, Bidski commented on README.md
> +On Windows, use Ubuntu in WSl. You can follow the instructions for setting it up on the [Getting Started NUbook page](https://nubook.nubots.net/guides/main/getting-started)
```suggestion
On Windows, use Ubuntu in WSL. You can follow the instructions for setting it up on the [Getting Started NUbook page](https://nubook.nubots.net/guides/main/getting-started)
```

2021-03-31 23:37 UTC, Bidski commented on README.md
> +3. Download Webots from source using the instructions on [GitHub](https://github.com/cyberbotics/webots/wiki#installation-of-the-webots-development-environment).
```suggestion
3. Download and build Webots from source using the instructions on [GitHub](https://github.com/cyberbotics/webots/wiki#installation-of-the-webots-development-environment). 
```

2021-04-09 02:50 UTC, KipHamiltons approved these changes
Sure

2021-04-09 02:54 UTC, Bidski approved these changes
Sure, why not

2021-04-09 03:44 UTC, merged