Add motor parameters
NUbots/NUWebots pull request #22
Opened 2021-04-14 03:08 UTC by TheCoolKidsTable

This PR adds:

-  Parameters for the MX106 and MX64 servos and assigns them to the correct motors. (MX106 for hip,knee,ankles and MX64 for arms/neck)
- PID gains for the motors (Obtained from Simscape)
- Sets selfCollision field for robot to TRUE

2021-04-23 11:13 UTC, ysims reviewed
Might need someone who can review the actual values :smile:

2021-04-23 11:13 UTC, ysims commented on protos/NUgus.proto
> +}
newline? :smile: Otherwise looks good

2021-05-15 03:09 UTC, xXBenjaminYoungXx commented
Add comments on which Dynamixel model is being represented on the Rotational Motor Object.

2021-05-18 03:40 UTC, Bidski requested changes
I think you should move the `boundingObject` changes to a separate PR. 

As for the backlash, I think we might find that they are expecting this as a measure of radians (because it is a HingeJoint). In which case 0.33 degrees (from the docs) is 0.005759587 radians (0.006). Have we tested with this value? Ludovic does warn against using a value that is too small

2021-05-23 11:56 UTC, Bidski approved these changes
LGTM

2021-05-24 04:37 UTC, Bidski submitted a review, later dismissed
Seems ok to me

2021-05-24 08:15 UTC, ysims approved these changes
LGTM

2021-05-24 08:16 UTC, merged