Adds build and configure scripts
NUbots/NUWebots pull request #40
Opened 2021-05-17 00:01 UTC by KipHamiltons

Adds the first `b` tools for NUWebots, with `./b build` and `./b configure`.
Depends on #39

2021-05-17 23:50 UTC, Bidski requested changes

2021-05-17 23:50 UTC, Bidski commented on scripts/configure.py
> +        pass
```suggestion
    os.makedirs("build", exist_ok=True)
```

2021-05-17 23:50 UTC, Bidski commented on scripts/configure.py
> +    command.extend([*args, b.project_dir])
I feel like we should make people use `ninja` as it is, overall, the better build tool
```suggestion
    command.extend([*args, b.project_dir, "-GNinja"])
```

2021-05-17 23:50 UTC, Bidski commented on scripts/build.py
> +        exitcode = os.system("cmake {}".format(b.project_dir)) >> 8
```suggestion
        exitcode = os.system("cmake {} -GNinja".format(b.project_dir)) >> 8
```

2021-05-17 23:50 UTC, Bidski commented on scripts/build.py
> +    command.insert(1, "-j{}".format(j))
```suggestion
    command = ["ninja", "-j{}".format(j), *args]
```

2021-05-17 23:50 UTC, Bidski commented on scripts/build.py
> +    if not os.path.isfile("Makefile"):
```suggestion
    if not os.path.isfile("build.ninja"):
```

2021-05-18 05:16 UTC, KipHamiltons commented
We will roll with ninja, as per your suggestion @Bidski. I'll make a PR to NUbook

2021-05-18 05:24 UTC, Bidski approved these changes
LGTM

2021-05-18 06:16 UTC, merged